###################### User route ###############################
#Sign up
POST http://localhost:3001/api/users 
Content-Type: application/json

{
    "username": "vntrieu4",
    "password": "vntrieu4",
    "name": "Vo Nhat Trieu",
    "img": "https://res.cloudinary.com/vntrieu/image/upload/v1619606477/user/ugiyfkwlq1k86qvbxkz6.jpg",
    "address": "CT",
    "phonenumber": "0123123123"
}
###Update user data
PATCH  http://localhost:3001/api/users/625f8fd82573248d344449b9
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVmOGZkODI1NzMyNDhkMzQ0NDQ5YjkiLCJpYXQiOjE2NTA0Njc3MjksImV4cCI6MTY1MDU1NDEyOX0.QRe3yX22JBxsQPJrrpDArd5j4L8Ps_CQXkKrwx-wapc

{
    "username": "vntrieu",
    "password": "vntrieu",
    "name": "Vo Nhat Trieu",
    "img": "https://res.cloudinary.com/vntrieu/image/upload/v1619606477/user/ugiyfkwlq1k86qvbxkz6.jpg",
    "address": "thi xa Long My - Hau Giang",
    "phonenumber": "0123123123"
}

###Update another user's data
PATCH  http://localhost:3001/api/users/625f910cc66d899132906824
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVmOGZkODI1NzMyNDhkMzQ0NDQ5YjkiLCJpYXQiOjE2NTA0Njc3MjksImV4cCI6MTY1MDU1NDEyOX0.QRe3yX22JBxsQPJrrpDArd5j4L8Ps_CQXkKrwx-wapc

{
    "username": "vntrieu123",
    "password": "vntrieu123",
    "name": "Vo Nhat Trieu",
    "img": "https://res.cloudinary.com/vntrieu/image/upload/v1619606477/user/ugiyfkwlq1k86qvbxkz6.jpg",
    "address": "thi xa Long My - Hau Giang",
    "phonenumber": "0123123123"
}

###Sign in
POST http://localhost:3001/api/users/login 
Content-Type: application/json

{
    "username": "vntrieu",
    "password": "vntrieu"
}

###Sign by token
POST http://localhost:3001/api/users/loginbytoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjI2MzI4OTI2NDc5ZDc4NThjYjNkMDU5IiwiaWF0IjoxNjUxODI0NTY3LCJleHAiOjE2NTE5MTA5Njd9.uVELjEOvHj_GAQeiQO_5DZNQg0eFD36FYgBmWe69eMk

###Get new token
POST http://localhost:3001/api/tokens
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY2NDA1MDNmMWY0MzI0N2MyNWRjZGMiLCJpYXQiOjE2NTEzMjY5NTl9.RFNF6VkUnojL3kk7J3x9BES2ox2Oz13BXAdqUola3C8"
}
###Logout
DELETE http://localhost:3001/api/tokens
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjVmOGZkODI1NzMyNDhkMzQ0NDQ5YjkiLCJpYXQiOjE2NTA0NjY4MjB9.u9RLZDjG1S2_NKGGVFj8i0bLxPohTE3utP8SvK8UrtE"
}

###################### Admin route ###############################
### Admin login
POST http://localhost:3001/api/admins/login 
Content-Type: application/json

{
    "username": "trucngan99",
    "password": "trucngan99"
}

###Admin login by token
POST http://localhost:3001/api/admins/loginByToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkI…yMTd9.VUA-geEiPO2cyMOAdU5NKIvxWGApknMq2bB0SFcmGJ8

###Get users
GET http://localhost:3001/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjI2MzI4OTI2NDc5ZDc4NThjYjNkMDU5IiwiaWF0IjoxNjUyMDc4ODY4LCJleHAiOjE2NTIxNjUyNjh9.AL57gO0i_rPNMYrLrorLtkTaptKmfnZoaLeK2Pqwf9c
###Delete user
DELETE http://localhost:3001/api/users/625f8fd82573248d344449b9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMDI4MzcxN2EzOTdmMmM5OWYxMDgiLCJpYXQiOjE2NTA1MjYyOTMsImV4cCI6MTY1MDYxMjY5M30.Lx4tARXi9OnXso2eqa5H5NlbKHk_WaPmM3iwirGPKy8

###Get books
GET http://localhost:3001/api/books?search=Love

###Create book
POST http://localhost:3001/api/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjI2MTAyODM3MTdhMzk3ZjJjOTlmMTA4IiwiaWF0IjoxNjUwNjQ5Nzg0LCJleHAiOjE2NTA3MzYxODR9.sfgmLr7a2SqtUUblubQUsjTzsHlgfnFqbEX9zVrMETw

{
    "name": "New book",
    "author": "Cixin Liu",
    "price": 16.11,
    "urlimg": "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/mid/9781/7849/9781784971618.jpg",
    "category": "Science Fiction"
}
### create book but no token provided
POST http://localhost:3001/api/books
Content-Type: application/json

{
    "name": "New book",
    "author": "Cixin Liu",
    "price": 16.11,
    "urlimg": "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/mid/9781/7849/9781784971618.jpg",
    "category": "Science Fiction"
}
###Delete book
DELETE http://localhost:3001/api/books/6277e3bcf3bad52a58d91892
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjI2MzI4OTI2NDc5ZDc4NThjYjNkMDU5IiwiaWF0IjoxNjUyMDI0MjI4LCJleHAiOjE2NTIxMTA2Mjh9.h79gmKKKQjdt96mhRim7CIgmaJKpb4PmoHbAHVw7WBs
###Update book
PATCH  http://localhost:3001/api/books/6262b6e0bbe7162a3e57ba85
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMDI4MzcxN2EzOTdmMmM5OWYxMDgiLCJpYXQiOjE2NTA2MzYxNTEsImV4cCI6MTY1MDcyMjU1MX0.MJjqQOkJoCJZ-P6CL5IN63P2ByO1FPL5jveO_4h5GhE

{
    "name": "New book UPDATE 2adsgsdg"
}

###create invoice
POST http://localhost:3001/api/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYyYmMyZmM0YjViMDMzZDFjYzgxMTgiLCJpYXQiOjE2NTA2NDAwNjksImV4cCI6MTY1MDcyNjQ2OX0.6bV2l2FBXMb2turn4tHecHJ7OJ3Ti6QZC0uomrKHgnI

{
    "name": "Nguyen Truc Ngan",
    "phonenumber": "012313123",
    "address": "Vinh Long",
    "date": "2022-04-22",
    "cart": [
        {
            "count": 2,
            "book": {
                "_id": "6262c6473f66821dd221475b",
                "name": "New book",
                "author": "Cixin Liu",
                "price": 16.11,
                "urlimg": "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/mid/9781/7849/9781784971618.jpg"
            }
        },
        {
            "count": 1,
            "book": {
                "_id": "6262c6473f66821dd221475b",
                "name": "New book",
                "author": "Cixin Liu",
                "price": 16.11,
                "urlimg": "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/mid/9781/7849/9781784971618.jpg"
            }
        }

    ],
    "totalamount": 48.33
}

### create invoice invalid data
POST http://localhost:3001/api/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY2NDA1MDNmMWY0MzI0N2MyNWRjZGMiLCJpYXQiOjE2NTA4NjgzMTcsImV4cCI6MTY1MDk1NDcxN30.HZcPvJ-cvCVSkVWn2aqfLHuvhnW_KVIUezfyphtR3QI


{
    "name": "Nguyen Truc Ngan",
    "phonenumber": "012313123",
    "address": "Vinh Long",
    "date": "2022-04-22",
    "cart": [],
    "totalamount": 0
}

###admin set state invoice
PATCH  http://localhost:3001/api/invoices/6262c5e03f66821dd2214758
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjYxMDI4MzcxN2EzOTdmMmM5OWYxMDgiLCJpYXQiOjE2NTA2MzYxNTEsImV4cCI6MTY1MDcyMjU1MX0.MJjqQOkJoCJZ-P6CL5IN63P2ByO1FPL5jveO_4h5GhE

{
    "state": "Cancel"
}

###Get categories
GET  http://localhost:3001/api/categories

###get users invoices
GET  http://localhost:3001/api/invoices
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjY2NDA1MDNmMWY0MzI0N2MyNWRjZGMiLCJpYXQiOjE2NTA4NjgzMTcsImV4cCI6MTY1MDk1NDcxN30.HZcPvJ-cvCVSkVWn2aqfLHuvhnW_KVIUezfyphtR3QI


